/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ReStudios_keyhandler_KeyHandler */

#ifndef _Included_org_ReStudios_keyhandler_KeyHandler
#define _Included_org_ReStudios_keyhandler_KeyHandler
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     org_ReStudios_keyhandler_KeyHandler
	 * Method:    m0
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_org_ReStudios_keyhandler_KeyHandler_m0
	(JNIEnv*, jclass);

	/*
	 * Class:     org_ReStudios_keyhandler_KeyHandler
	 * Method:    m3
	 * Signature: (I)Z
	 */
	JNIEXPORT jboolean JNICALL Java_org_ReStudios_keyhandler_KeyHandler_m3
	(JNIEnv*, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
